from enum import Enum


class RoomCategory(str, Enum):
    # Park 100 Complex (New Dorms)
    PARK_SHARED_2BR = "PARK_SHARED_2BR"
    PARK_SHARED_3BR = "PARK_SHARED_3BR"
    PARK_STUDIO = "PARK_STUDIO"
    PARK_COUPLES = "PARK_COUPLES"
    # Ilanot Complex (Standard Dorms)
    ILANOT_SHARED_1BR = "ILANOT_SHARED_1BR"
    ILANOT_SHARED_2BR = "ILANOT_SHARED_2BR"
    ILANOT_PRIVATE = "ILANOT_PRIVATE"
    ILANOT_SHARED_LARGE = "ILANOT_SHARED_LARGE"
    ILANOT_STUDIO = "ILANOT_STUDIO"
    ILANOT_COUPLES = "ILANOT_COUPLES"


class ListingType(str, Enum):
    LEASE_TRANSFER = "LEASE_TRANSFER"
    SWAP_REQUEST = "SWAP_REQUEST"


class LeaseTransferStatus(str, Enum):
    OPEN = "OPEN"
    MATCHED = "MATCHED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class SwapRequestStatus(str, Enum):
    OPEN = "OPEN"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    FULLY_MATCHED = "FULLY_MATCHED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class MatchStatus(str, Enum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class TransactionStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
